// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.WebAPI.Data;

namespace Projeto.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Projeto.WebAPI.Model.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bandeira");

                    b.Property<string>("Cvv");

                    b.Property<string>("Data_Expiracao");

                    b.Property<string>("Numero");

                    b.Property<string>("Titular");

                    b.HasKey("Id");

                    b.ToTable("Cartao");
                });

            modelBuilder.Entity("Projeto.WebAPI.Model.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data_Transacao");

                    b.Property<int?>("SolicitacaoId");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Projeto.WebAPI.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int>("Qtde_Estoque");

                    b.Property<double>("Valor_Unitario");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Projeto.WebAPI.Model.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CartaoId");

                    b.Property<int>("Produto_Id");

                    b.Property<int>("Qtde_Comprada");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Projeto.WebAPI.Model.Compra", b =>
                {
                    b.HasOne("Projeto.WebAPI.Model.Solicitacao", "Solicitacao")
                        .WithMany()
                        .HasForeignKey("SolicitacaoId");
                });

            modelBuilder.Entity("Projeto.WebAPI.Model.Solicitacao", b =>
                {
                    b.HasOne("Projeto.WebAPI.Model.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
